### ISSUE TITLE
Consider what to do now libsass is no longer being developed

### ISSUE THREAD

**Issue by stefanv** [bep/golibsass#6]
See the [deprecation announcement](https://sass-lang.com/blog/libsass-is-deprecated) on the project site.

**Comment by bep** [comment]
There is this: https://github.com/bep/godartsass -- I'm not sure what more **I can do?**.

**Comment by stefanv** [comment]
I came to this repository from a Hugo discussion link, presuming that this was the library used by Hugo to translate SASS.  If that is no longer the case, then this topic is moot.  A pointer to the new project in the README or repository description could help others avoid the same confusion?

Thank you for your work on Hugo.  It is much appreciated!

**Comment by bep** [comment]
Hugo currently support both (there is a provider option, see the documentation)).
