### ISSUE TITLE
mac m1 13.2 , Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. 

### ISSUE THREAD

**Issue by Yansre** [bep/golibsass#8]
In file included from json.cpp:2:
../../workspace/golang/pkg/mod/github.com/bep/golibsass@v1.1.0/internal/libsass/../../libsass_src/src/json.cpp:1289:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'

**Comment by bep** [comment]
We have a patch for this since very long.
